### ISSUE TITLE
Transfer to FIRSTMap organization

### ISSUE THREAD

**Issue by ErikBoesen** [FIRSTMap/FIRSTmap-scraper#1]
Could this be transferred?

**Comment by GeeII** [comment]
I tried.  It tells me "You don’t have the permission to create repositories on FIRSTMap".  Should it be going somewhere else?

**Comment by ErikBoesen** [comment]
I have to have admin, not write, permissions to transfer the repository.

**Comment by GeeII** [comment]
How?  I figured I could add them once I had you as a collaborator, but don't see any way there either.

**Comment by GeeII** [comment]
Found  this https://help.github.com/articles/managing-an-individual-s-access-to-an-organization-repository/ but got stuck at step 2 or 3 as we aren't both members of any organization?

Anyway, I'll be offline for the next six hours or so.

**Comment by ErikBoesen** [comment]
This repository is not tied to an organization, it's on your personal account.
![](https://user-images.githubusercontent.com/5923662/42423198-85dedf1c-82c4-11e8-955f-f31aef947ea5.png)
![](https://user-images.githubusercontent.com/5923662/42423199-85ee21fc-82c4-11e8-8a92-fdf4b056fd8a.png)

**Comment by GeeII** [comment]
I guess I missed it?  I had a notification flagged in two separate windows, but when I clicked on the "bell", it showed no new notifications.

**Comment by GeeII** [comment]
Looks like it worked!  The repository disappeared from my profile and appeared in FIRSTmap.  I have already created my own fork.

**Comment by GeeII** [comment]
Just curious, what happens to my local copy of the scraper?  The fork I made has the same name but is inherently something a bit different than it was a few minutes ago.  Will this still work, or do I need to check it out again?

**Comment by ErikBoesen** [comment]
@GeeII It'll still work just fine, although if you try to push it will push to your fork. Typically if you transfer or rename a repository GitHub will just redirect any pushes. However since you've forked something and that fork now has the same URL as the old repository any pushes will go there.

Thanks for transferring!
